#pragma config(Motor,  port1,           Left,          tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           Front,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           Back,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          Right,         tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Controller 1/2, Stick L/R, Axis X/Y
#define C1LY						                vexRT[Ch3]
#define C1RX							              vexRT[Ch1]
#define C1LX								            vexRT[Ch4]

task main()
{
	while (true)
	{
		// Y component, X component, Rotation
		motor[Front] = -C1LX - C1RX; // Front
		motor[Left] = -C1LY - C1RX; // Left
		motor[Right] =  C1LY - C1RX; // Right
		motor[Back] =  C1LX - C1RX; // Back
		// Motor values can only be updated every 20ms
		wait1Msec(20);
	}

}
